version: "3.8"

name: aws-vpc-inbound-action

services:

  app:
    image: node:20-alpine
    container_name: app.aws-vpc-inbound-action.dev
    user: ${UID:-1000}
    working_dir: /node/app
    volumes:
      - ./:/node/app
    environment:
      # Bugfix. See: https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
      NODE_OPTIONS: --experimental-vm-modules
      NPM_CONFIG_UPDATE_NOTIFIER: false
    command: ["tail", "-f", "/dev/null"] # Dummy long process